### ISSUE TITLE
Captioning and ASL interpretation

### ISSUE THREAD

**Issue by elisenovitski** [gordonwatts/snowmass-attendance#3]
The summary section on the first page talking about ASL is not complete/representative; it underestimates the number of people who need ASL or live captioning to participate, and it doesn't cover the fact that full captioning would be an appropriate substitute for ASL (i.e., ASL was only requested as a backup for cases where live captioning isn't available.) The following information is more complete:
- 16 people who have checked at least one of "Live captioning is necessary for my full participation" and "ASL interpretation is necessary for my full participation if sessions are not live-captioned." 
- 77 people who did not check either of those did check "Live captioning would be helpful, but not necessary for me."

**Comment by gordonwatts** [comment]
This was fixed with the update!
